version: '3.8'

services:

  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=meusecret123
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

  webserver:
    image: nginx:alpine
    restart: always
    volumes:
      - wordpress:/var/www/html
      - nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443

  wordpress:
    image: wordpress:5.1.1-fpm-alpine
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mysql-db:3306
      - WORDPRESS_DB_USER=admin
      - WORDPRESS_DB_PASSWORD=aquelasenhatop
      - WORDPRESS_DB_NAME=mydb
    volumes:
      - wordpress:/var/www/html

volumes:
  db-data:
  wordpress:
  nginx:
